name: CI

on:
  push:
    branches: debug
  pull_request:
    branches: debug

jobs:
  install_meson:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-2019

    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: npm install
      - run: npx xpm install
      - run: npx xpm run build
      - run: |
          dir
          dir wrappers
          dir content\bin
          content\bin\meson
          content\bin\meson help
        if: runner.os == 'Windows'
      - name: Test
        run: npx xpm run test
